# Use the official Python image from the Docker Hub
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt app/requirements.txt

# Install the dependencies
RUN pip install --no-cache-dir -r app/requirements.txt

# Copy the rest of the application code into the container
COPY . app/

# Expose the port that Streamlit will run on
EXPOSE 8501

# Command to run the Streamlit app

CMD ["streamlit", "run", "streamlit_app.py"]