
services:
  frontend:
    build: frontend
    ports:
      - 7860:7860
    depends_on:
      - backend
    volumes:
        - ./frontend:/app

  backend:
    build: backend
    expose:
      - "8501"
    ports:
      - 8501:8501
    volumes:
      - ./backend:/app
